{{- if .Values.querier.ingress.enabled }}
{{- range .Values.querier.ingress.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "thanos.fullname" . }}-querier
  labels: {{- include "thanos.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .certificate | b64enc }}
  tls.key: {{ .key | b64enc }}
---
{{- end }}
{{- end }}
