---
# Source: thanos/templates/querier/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-thanos-querier
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
---
# Source: thanos/templates/query-frontend/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: RELEASE-NAME-thanos-query-frontend
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
---
# Source: thanos/templates/querier/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-thanos-querier
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
    - port: 10901
      targetPort: grpc
      protocol: TCP
      name: grpc
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: querier
---
# Source: thanos/templates/query-frontend/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: RELEASE-NAME-thanos-query-frontend
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  type: ClusterIP
  ports:
    - port: 9090
      targetPort: http
      protocol: TCP
      name: http
      nodePort: null
  selector:
    app.kubernetes.io/name: thanos
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/component: query-frontend
---
# Source: thanos/templates/querier/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-thanos-querier
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: querier
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: querier
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        helm.sh/chart: thanos-2.5.0
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: querier
    spec:
      
      serviceAccount: RELEASE-NAME-thanos-querier
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: querier
          image: bitnami/thanos:0.15.0-scratch-r3
          imagePullPolicy: "IfNotPresent"
          args:
            - query
            - --log.level=info
            - --grpc-address=0.0.0.0:10901
            - --http-address=0.0.0.0:10902
            - --query.replica-label=replica
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
            - name: grpc
              containerPort: 10901
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:
---
# Source: thanos/templates/query-frontend/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: RELEASE-NAME-thanos-query-frontend
  labels:
    app.kubernetes.io/name: thanos
    helm.sh/chart: thanos-2.5.0
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: query-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: thanos
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/component: query-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: thanos
        helm.sh/chart: thanos-2.5.0
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: query-frontend
    spec:
      
      serviceAccount: RELEASE-NAME-thanos-query-frontend
      securityContext:
        runAsUser: 1001
        fsGroup: 1001
      containers:
        - name: query-frontend
          image: bitnami/thanos:0.15.0-scratch-r3
          imagePullPolicy: "IfNotPresent"
          args:
            - query-frontend
            - --log.level=info
            - --http-address=0.0.0.0:10902
            - --query-frontend.downstream-url=http://RELEASE-NAME-thanos-querier:9090
          ports:
            - name: http
              containerPort: 10902
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 30
          resources:
            limits: {}
            requests: {}
          volumeMounts:
      volumes:
